### ISSUE TITLE
create script to import mff and write bids file

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#1]

**Comment by georgebuzzell** [comment]
![image](https://user-images.githubusercontent.com/71228105/110360419-afa94100-800c-11eb-9c8d-d67cf2b9b4e3.png)

**Comment by Jonhas** [comment]
@georgebuzzell I'm having some trouble finding a .mff filetype to be able to read from. The zip folder after unzipped only provides several xml files such as shown in the image. , where the contents folder does not contain much either.
![image](https://user-images.githubusercontent.com/45021859/111012950-5f5f1580-8363-11eb-9e34-75545a3eb45e.png)

**Comment by georgebuzzell** [comment]
Yes, this is the thing I was mentioning about how the file format of these files is messed up sometimes. Basically, after you unzip the file, the highest level folder should actually not be a folder you can open, but a proprietary .mff zip file. There are two things to try:
1) try to import this folder as if it is a file without an extension (don't think this will work"
2) add ".mff" to the end of the folder name to allow you to reference the whole folder as one .mff file (which is how it should appear in the first place.

let me know if neither of these options work and/or you have further questions.

**Comment by Jonhas** [comment]
Hello @georgebuzzell i just put in a pull request, was able to read raw EGI data through mff file, but getting some issues regarding writing raw bids. This stems from a signal1.bin file within the mff file  which is whats causing the error to shoot up. The NDARAB793GL3 folder given was corrupted. Doing the following is what helped me to fix it. 
https://superuser.com/questions/23290/terminal-tool-linux-for-repair-corrupted-zip-files
