### ISSUE TITLE
Web-based BIDS validator detects participants.tsv as not BIDS compliant.

### ISSUE THREAD

**Issue by DMRoberts** [NDCLab/baseEEG#102]
The web-based BIDS validator(https://bids-standard.github.io/bids-validator/) detects an error, that participants.tsv is not BIDS compliant due to a missing value.

![image](https://user-images.githubusercontent.com/833695/118072711-6d87dd00-b378-11eb-80f0-bdab78e7e7bf.png)

**Comment by F-said** [comment]
resolved with merged PR #105
