### ISSUE TITLE
Error on importing BIDS example dataset into EEGLAB

### ISSUE THREAD

**Issue by DMRoberts** [NDCLab/baseEEG#103]
As noted by @yanbin-niu ( https://github.com/NDCLab/baseEEG/issues/25#issuecomment-833462228 ), attempting to import our BIDS formatted data into EEGLAB generates an error. The error suggests that the the format of the acquisition time within *scans.tsv isn't BIDS compliant.

**Comment by F-said** [comment]
Reposting for visibility 

> 
> In regards to the timestamp error caught by EEGLAB, I think this is a mistake in the EEGLAB bids validator:
> 
> The [bids-EEG doc](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html) states:
> 
> > Note that the date and time information SHOULD be stored in the Study key file ([scans.tsv](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#scans-file)). Date time information MUST be expressed as indicated in [Units](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#units)
> 
> The [common principles doc](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#units) that describes the units then states:
> 
> > Date time information MUST be expressed in the following format YYYY-MM-DDThh:mm:ss[.000000][Z] (year, month, day, hour (24h), minute, second, optional fractional seconds, and optional UTC time indicator).
> 
> So while the addition of fractional seconds is optional, it's still valid.
> 
> And the [_scans_tsv](https://github.com/mne-tools/mne-bids/blob/main/mne_bids/write.py) function of mne-bids explictly uses franctional seconds on line 387:
> 
> ```python
> elif isinstance(meas_date, datetime):
>     # for MNE >= v0.20
>     acq_time = meas_date.strftime('%Y-%m-%dT%H:%M:%S.%fZ')
> ```

**Comment by DMRoberts** [comment]
I played around with this a bit in EEGLAB. Our timestamp has fractional seconds and the timezone indicator ('Z' to indicate UTC). The presence of fractional sections and / or the timezone indicator seems to cause the EEGLAB BIDS validator to fail:

```
1: [ERR] Entries in the "acq_time" column of _scans.tsv should be expressed in the following format YYYY-MM-DDTHH:mm:ss (year, month, day, hour (24h), minute, second; this is equivalent to the RFC3339 “date-time” format.  (code: 84 - ACQTIME_FMT)
		./sub-NDARAB793GL3/ses-01/sub-NDARAB793GL3_ses-01_scans.tsv
			@ line: 2
			Evidence: 2017-05-12T15:07:18Z
```


```
	1: [ERR] Entries in the "acq_time" column of _scans.tsv should be expressed in the following format YYYY-MM-DDTHH:mm:ss (year, month, day, hour (24h), minute, second; this is equivalent to the RFC3339 “date-time” format.  (code: 84 - ACQTIME_FMT)
		./sub-NDARAB793GL3/ses-01/sub-NDARAB793GL3_ses-01_scans.tsv
			@ line: 2
			Evidence: 2017-05-12T15:07:18.000000
```

Both have to be removed for the EEGLAB BIDS validation to pass. 

As @F-said mentioned our timestamp seems to be in BIDS spec so this is probably a EEGLAB BIDS validation issue. I tried to look at what they were doing, but the BIDS validation in EEGLAB seems to call a compiled binary for performing the validation.

**Comment by georgebuzzell** [comment]
@DMRoberts and @F-said am I correct in understanding that we are fully bids compliant, and our data higher precision (fractional second) timestamps? And, that the reason our data fails on importing into eeglab is given that fractional timestamps are not allowed by eeglab? 

If so, I am fine with calling this issue "resolved" for now. and, as a future "want" but not immediate "need" that we develop a function to convert our data to a format compatible with eeglab bids (i.e. rounding all time stamps up/down to nearest integer).

**Comment by F-said** [comment]
Closing and moving discussion to #109
