### ISSUE TITLE
Agenda 5/14

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#104]
Everyone using the most recent bids folder on the drive?

Updates to bids folder structure, in light of derivatives? Weren't we going to put the raw data in a "raw" folder?

Creation of the main script

Workflow updates (zenhub, issues, labels, etc)

Integrating with bids validator
-current plan? Considering rewriting in JS?

**Comment by F-said** [comment]
- going forward with FASTER for bad-channels
- integrated pipeline folder structure 
- plan for baseEEG on the cluster

**Comment by Jonhas** [comment]
- Agile methodology with zenhub?

**Comment by F-said** [comment]
- cool with deleting merged branches?

**Comment by DMRoberts** [comment]
- We currently develop on feature branches labelled with our names, which get merged into feature branches through pull-requests. For example dev-feature-io-dan is merged into dev-feature-io. But do we have a protocol for when dev-feature-io for example would be merged into the branch dev?

- We added .DS_Store to the .gitignore, but we should also delete any .DS_Store files that were committed to the repo prior to being added to .gitignore

**Comment by SDOsmany** [comment]
- Are the functions also returning the raw file? or just the output_dict? How is the raw reference being passed down?

**Comment by georgebuzzell** [comment]
Fractional time stamps and eeglab bids. "Done" for now and create future issue when time? https://github.com/NDCLab/baseEEG/issues/103#issuecomment-840988020

**Comment by georgebuzzell** [comment]
Collating outut_dicts from various functions/steps called in main https://github.com/NDCLab/baseEEG/pull/101#issuecomment-840933369

**Comment by georgebuzzell** [comment]
**Updated agenda (merging comments)**

**Admin**
Everyone using the most recent bids folder on the drive?


**Big issues**
Pipeline overview and creation of the main script
-"raw" being passed to each function and returned
-Collating outut_dicts from various functions/steps called in main #101 (comment)
-Updates to bids folder structure, in light of derivatives? Weren't we going to put the raw data in a "raw" folder?

Moving to HPC

Workflow updates (zenhub, issues, labels, etc)
-agile
-merged branches get deleted
-We currently develop on feature branches labelled with our names, which get merged into feature branches through pull-requests. For example dev-feature-io-dan is merged into dev-feature-io. But do we have a protocol for when dev-feature-io for example would be merged into the branch dev?
-We added .DS_Store to the .gitignore, but we should also delete any .DS_Store files that were committed to the repo prior to being added to .gitignore


**Specifics**

Bids validator
-Fractional time stamps and eeglab bids. "Done" for now and create future issue when time? #103 (comment)

Moving forward with FASTER for bad-channels
