### ISSUE TITLE
Update folder structure

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#107]
@DMRoberts please determine if we will store the "raw data" in "raw" or directly inside the bids folder.  

Please update the roadmap accordingly, also please update feature-io if necessary. 

Done = PR for updated roadmap accepted.

@DMRoberts please communicate with @SDOsmany as he needs to know the updated folder structure for #95

**Comment by georgebuzzell** [comment]
@DMRoberts I propose going with storing inside "raw" unless you disagree?

**Comment by F-said** [comment]
closed with merge #132
