### ISSUE TITLE
Discussions about python versions for running CI test.

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#11]
Currently, we have 3.5,3.6,3.7,3.8 version to run CI testing.

**Comment by georgebuzzell** [comment]
@DMRoberts @Jonhas @yanbin-niu @DavyNeat Any comments here? The default is to check the last 4 versions when ci runs, that goes back about 6 months. Sound good to all?

**Comment by georgebuzzell** [comment]
We decided to move forward with the CI checking the 4 most recent versions of python. We can change this standard as needed in the future.

@yanbin-niu has kindly implemented this and we are very grateful to her!! :)
