### ISSUE TITLE
update feature io to write to new format for folder structure

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#126]
Update feature-io to write to the new folder structure. Follow format described here: https://github.com/NDCLab/baseEEG/issues/95#issuecomment-840463003

Update roadmap to include a description of new folder structure

Export new example data set after changes made to feature io

PR for new feature io code, new dataset that was uploaded and roadmap changes

Once PR confirmed, merge in and communicate to all via gh and slack

DONE= PR reviewed/merged and all updated on changes

**Comment by F-said** [comment]
closed with merge #132
