### ISSUE TITLE
5/28/2021

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#128]
**Updates**
* Issues template #117 set up to drive issue generation & completion
* Outer-loop to loop over subjects, sessions, tasks & runs
* Singularity container set up on HPC

**Blocks/Challenges**
* Will this be made available as a package installable through "pip"?

**Next Actions**
* PR dev into main 
* PR pipeline features into dev
* PR main pipeline into dev
* Create integration branch to integrate structure and features

**Comment by georgebuzzell** [comment]
HPC folder structure and integration with git/github

Should we officially switch to GitFlow model now, or wait? (release branches)
-Regardless, should we switch to a fork and pull model now, or wait? or, plan on future hybrid model?
