### ISSUE TITLE
Create outer loop to handle pipeline on subject/participant/session/run

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#138]
**Describe the feature effect or output**
Outer loop to analyze intended subjects/etc based on user_params

**Which part of the pipeline does this satisfy if any**
Main pipeline

**What is the minimum for this feature to be complete?**

- user params includes info on which subject/session/run/task to analyze
- pipeline loops on info

**Comment by F-said** [comment]
Should users be able to specify tasks/runs/sessions, or only subjects?

**Comment by georgebuzzell** [comment]
@F-said they should be able to specify subjects, tasks, sessions, runs
