### ISSUE TITLE
Move full CMI EEG data set over to hpc

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#169]
**Describe the feature effect or output**
A succinct description of what the feature will output or affect in the pipeline. 

**Which part of the pipeline does this satisfy if any**
Within the roadmap of [contributing.md](https://github.com/NDCLab/baseEEG/blob/dev/contributing.md), which part does this feature fulfill (unless it is a new suggestion). 

**What is the minimum for this feature to be complete?**
Which end result needs to happen for this feature to be *done*, even if this minimum leads to new issues (testing/documenting/another feature request).

**Comment by F-said** [comment]
transfer initiated via globus, closing on completion

**Comment by F-said** [comment]
Complete
