### ISSUE TITLE
Feature-filter

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#24]
Feature-filter
-High pass filter the data using mne function
-write to annotations file the details of the filter applied to data

**Comment by yanbin-niu** [comment]
@georgebuzzell The following should work

```
import matplotlib
import pathlib
import mne
import mne_bids

# Read BIDS data
bids_root = pathlib.Path('raw_data/eegmatchingpennies')
bids_path = mne_bids.BIDSPath(subject='05',
                              task='matchingpennies',
                              datatype='eeg',
                              root=bids_root)
raw = mne_bids.read_raw_bids(bids_path)

# filter
raw.load_data()
raw_filtered = raw.copy().filter(l_freq=0.1, h_freq=40)

raw_filtered.plot()
```

**Comment by georgebuzzell** [comment]
@yanbin-niu this is great! Minor change is to change l_freq=.1 to l_freq=.3 

Typically, a lower bandpass of .1 (as you suggest) or even lower, at .01, would be preferred, but for the EGI system, which is a "high impedance system", the manufacturers recommend .3 hz. this approximately lines up with a relatively recent paper testing this by Luck and colleagues as well. 

If you want, please go ahead and create a branch with your code (called feature-filter-yanbin, test, and then do a pull request to feature-filter. I will run tests on your code before merging in. :) HOwever, no rush on this, of course!

PS: for now, this basic .3-40 hz filter will be fine, however, we may want to modify the specifics of the filter in a later iteration of the pipeline. In particular, we may want to modify the "roll off" of the high pass filter. However, please do not worry about this for now. I am only mentioning it now so that it is not a surprise later. What you have here is really great for now!! :) Thank you!!

**Comment by yanbin-niu** [comment]
@georgebuzzell I submitted a new pull request. To test, you need a folder structure "raw_data/eegmatchingpennies" (sorry, I should make it easier.). Note, there is no dash in "eegmatchingpennies" (when you first unzip it, it is called "eeg-matchingpennies").

**Comment by georgebuzzell** [comment]
@yanbin-niu Thank you! Will test this am (EST)!

**Comment by georgebuzzell** [comment]
@yanbin-niu Do you get this warning when running?
![image](https://user-images.githubusercontent.com/71228105/114566546-64ec9b80-9c40-11eb-805e-8633b0f10e63.png)

**Comment by georgebuzzell** [comment]
Here is my directory structure:
![image](https://user-images.githubusercontent.com/71228105/114567027-d7f61200-9c40-11eb-9433-ae277547b12b.png)

note that I have the eeg.json file at the level of "eegmatchingpennies" this SHOULD be read properly by MNE BIDS as being applied to all files, including sub-05. However, that is not the case, or at least not based on the parameters to mne bids currently. Perhaps I have something wrong on my end, though?

**Comment by yanbin-niu** [comment]
@georgebuzzell Based on the discussion from our last meeting, I slightly edited it a little bit to be capable of receiving parameters. The new script goes like this:

```
import matplotlib
import pathlib
import mne
import mne_bids

def filter_raw(raw, l_freq=0.3, h_freq=40) -> mne.io.Raw:
    raw.load_data()
    return raw.copy().filter(l_freq=l_freq, h_freq=h_freq)

# Read BIDS data
bids_root = pathlib.Path('raw_data/eegmatchingpennies')
bids_path = mne_bids.BIDSPath(subject='05',
                              task='matchingpennies',
                              datatype='eeg',
                              root=bids_root)

raw = mne_bids.read_raw_bids(bids_path)
raw.plot()

# filter
raw_filtered = filter_raw(raw)

raw_filtered.plot()
```

I have this tested (.ipynb and .py) in our new docker container and it can run properly.

Output for running .py file:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/79607547/115134061-a796e500-a03f-11eb-8fd9-359361f6f1b4.png">

The plotting before vs after filtering (plot inline)
<img width="527" alt="image" src="https://user-images.githubusercontent.com/79607547/115133457-fbeb9600-a03a-11eb-82fe-6a4988ebd8e2.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/79607547/115133465-102f9300-a03b-11eb-9f1b-cfda82054cac.png">

**Comment by yanbin-niu** [comment]
@georgebuzzell Do you have some preferences for the function naming? I mean probably we want neat function names for say, filter, ice, epoch etc…. For example, for filter function, we can name it “baseeeg_processing_filter”. And for epoch and ica, we name it “baseeeg_processing_epoch” and “baseeeg_processing_ica”. For IO feature, we can call "baseeeg_io_xxxx". I mean, I am not a good namer and I personally do not have any preferences for how to name the functions. However, I think we do want standardized and organized names across our processing functions. Those are just my thoughts and maybe this is unnecessary or something I miss here.

**Comment by georgebuzzell** [comment]
@yanbin-niu this is all GREAT!

The code looks good. Please do a PR. :)

Excellent point about naming conventions. We do absolutely want to standardise naming conventions. I like your naming conventions you propose a lot! One very minor change: change the part that says "processing" to "preprocessing". Otherwise, I say your naming suggestions should be the standard! :)

@F-said can you please create a new issue for defining naming standards for functions, and other relevant naming standards/conventions that we should consider across lab code? Please loop in @yanbin-niu here for her great insights! 

Thank you!
