### ISSUE TITLE
Competition to name our pipeline!!

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#244]
All, we really need to come up with a name for our pipeline. At the very least, a working name for the time being.

*Whoever suggests the name that is ultimately selected will receive a $20 Amazon gift card.* 

The essence of what we want to capture is as follows:

-EEG
-preprocessing pipeline
-open source
-pipeline
-scalable (i.e. can run on hpcs 
-reproducible (i.e. use of docker/singularity and heavy annotation of steps)
-easy to use for novices, but also reflects high-quality pipeline
-python (not many python eeg pipelines)
-We MIGHT want to emphasize relevance for developmental data (but not necessary)
-Heavily annotated
-flexible

Of course, we don't need to hit all those terms in the pipeline name. But something that captures the essence of those things. And, above all, the most important feature is that this pipeline is fully open source (but not just sharing code, but also, it does not rely on a licensed program to run, like Matlab, which most still require). 

@DMRoberts @F-said @yanbin-niu @SDOsmany @Jonhas @stevenwtolbert @CamachoBry @jessb0t (yes including you on purpose, Jess!)

Please suggest names, no bad suggestions. The best names will capture the concepts above in a clever acronym that is short and catchy.

**Comment by jessb0t** [comment]
@georgebuzzell: Is this pushing it too far? 😂 

**P**ipeline for **R**eproducible **E**EG with a **P**ython, **R**adically-**O**pen, **C**ustomizable, **E**xpedient, and **S**calable **S**tructure (PRE-PROCESS)

**Comment by georgebuzzell** [comment]
@jessb0t quite clever for sure, but maybe a bit too long. But, lots of great stuff in there!!

**Comment by F-said** [comment]
## PEP

Python EEG Pipeline

## POPED

**P**ython **O**pen-source **P**ipeline for **E**EG **D**ata

## POP

**P**ython **O**pen-source **P**ipeline 

## Q-PED

**Q**-PED **P**rocesses **E**EG **D**ata!

**Comment by jessb0t** [comment]
**SHARE:** **S**calable, **H**eavily-**A**nnotated, **R**eproducible, **E**EG pipeline
**PREP:** **P**ipeline for **R**eproducible **E**EG with **P**ython
**PEPPER:** **P**ython-based, **E**asy, **P**re-**P**rocessing, **E**EG **R**eproducibility pipeline

**Comment by georgebuzzell** [comment]
OK, the other day in the meeting @DMRoberts suggested a play on the Maryland Analysis of Developmental EEG (MADE) Pipeline name: the Florida Analysis of Developmental EEG (FADE). Until now, that was the current front runner.

But... My new (current) favorite and the new front runner is definitely:
SHARE: Scalable, Heavily-Annotated, Reproducible, EEG pipeline

Super clever, @jessb0t ! I like this a lot, becuase it includes just about every key concept in the name:
-Scalable (i.e. HPC ready)
-Heavily annotated
-Reproducible (i.e., built to run in a container
-and, while "open source" is not a specific word in the title, the acronym "SHARE" can be said to be an homage to the open-source (i.e. sharable) nature of the pipeline.

Also, who is going to dislike a pipeline called something positive like "SHARE" :) Super clever and great suggestion!

OK, all this is the new name to beat. I am going to set the final deadline for the competition for this coming Friday (the 6th).

@DMRoberts @F-said @yanbin-niu @SDOsmany @Jonhas @stevenwtolbert @CamachoBry @jessb0t

**Comment by georgebuzzell** [comment]
OK, so I needed to take a little break from finishing up the paper that @yanbin-niu and I are working on, and I couldn't help but mock up some possible logos for the "SHARE Pipeline" (assuming we go with that). Going to paste these here and I would love to hear what others think. Do you not care for any of them? Are there certain ones or styles you like more? And in particular, which is both aesthetically pleasing but also helps to capture the essence of the pipeline (i.e. open-source and SHAREable).

Please note that these are super quick drafts. Thus, don't really pay attention to artifacts in the images, poor cropping, etc. Similarly, don't pay much attention to the color per se, as that might all change. 

OK, here they are, in no particular order; curious to hear what you think @F-said @yanbin-niu @DMRoberts @SDOsmany @stevenwtolbert @jessb0t @Jonhas 

![image](https://user-images.githubusercontent.com/71228105/127741639-1a47842c-7ec5-4011-a57a-62b4e46439ae.png)

PS: I am obviously pretty sold on this new name suggestion by @jessb0t, but happy to still consider alternatives this week...

**Comment by yanbin-niu** [comment]
@jessb0t brilliant idea!

@georgebuzzell  I like those ones. Especially the top left one (two brains), as well as the one blow it (with the signal). I also like the other two on the right side, which give a sense of conciseness.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/79607547/127758391-3a7739cc-a7a1-491d-a2d6-242f351ddfe7.png">

**Comment by jessb0t** [comment]
😊 Aw!  Thanks, @georgebuzzell and @yanbin-niu !

My favorite is this one:
![image](https://user-images.githubusercontent.com/77893711/127867974-37f2d7ff-88bb-4fa3-87bf-2a2eee629dbd.png)
I like it's simplicity, that it reminds me of an electrode cap, and that it works in greyscale. 🙂 

My least favorite are the ones with multiple brains because, at a quick glance, they kind of look like chat bubbles. 😝

**Comment by F-said** [comment]
![image](https://user-images.githubusercontent.com/26397102/127882783-24b4e191-31f9-4305-8716-82b3fc98a881.png)
 
@jessb0t I'm a big fan of PEPPER as well 😤

@georgebuzzell 
I really like this logo, since the arrows can have multiple interpretations:
- the pipeline process 
- pulling repo/pushing contributions
- scalable software

**Comment by F-said** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/26397102/128071132-e22f95da-4822-4e96-89b2-3ad5258bba81.png)

**Comment by georgebuzzell** [comment]
@jessb0t @F-said @yanbin-niu @DMRoberts @stevenwtolbert @Jonhas @SDOsmany 

OK, after much deliberation and back and forth. And based on the clear favorite from many of you (despite my beautiful designs for "SHARE"!) that the winner is:

PEPPER: Python-based, Easy, Pre-Processing, EEG Reproducibility pipeline

So, I am renaming the repo accordingly. Please note that until we actually publish, the pipeline name is still subject to change. But, this will be the name going forward.
