### ISSUE TITLE
Feature-ica

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#26]
Feature-ica
This feature includes three main (and sequential) steps: 1. Prepica; 2. Ica; 3. Rejica
Overview: ICA requires a decent amount of stationarity in the data. This is often violated by raw EEG. One way around this is to first make a copy of the eeg data. For the copy, use automated methods to detect noisy portions of data and remove these sections of data. Run ICA on the copied data after cleaning. Finally, take the ICA weights produced by the copied dataset and copy them back to the recording prior to making a copy (and prior to removing sections of noisy data). In this way, we do not have to “throw out” sections of noisy data, while at the same time, we are able to derive an improved ICA decomposition.
Prepica
-Make a copy of the eeg recording
-For the copied data: high-pass filter at 1 hz
-For the copied data: segment/epoch (“cut”) the continuous EEG recording into arbitrary 1-second epochs
-For the copied data: Use automated methods (voltage outlier detection and spectral outlier detection) to detect epochs -that are excessively “noisy” for any channel
-For the copied data: reject (remove) the noisy periods of data
-Write to the annotations file which segments were rejected and based on what metrics
Ica
-For the copied data: run ica
-Copy the ica weights from the copied data back to the data pre-copy
Rejica
-Using automated methods (TBD) identify ica components that reflect artifacts
-Remove the data corresponding to the ica-identified-artifacts
-Write to the annotations file which ica components were identified as artifacts, based on what metrics, and whether they were removed

**Comment by georgebuzzell** [comment]
@yanbin-niu Please do not hesitate at all to reach out to me to discuss this. I am MORE THAN HAPPY to jump on a call, or write things out here, to facilitate. Very much appreciate you taking the initiative here! :)

**Comment by georgebuzzell** [comment]
@yanbin-niu Great work and great questions! Comments and responses to your questions below. But again, really great work!!

"I am not really understand "arbitrary 1-second epochs" (question 1, let m know if understand it correctly). I assume it means the epochs do not need to be based on any event. So, for mne, it recommends to make a new event array and then epoch based on the new events"
- Yes; correct! Arbitrary here means they are not tied to any events in particular. Also, we do not want any overlap in the epochs (that is important). So, we want to segment the copied data into 1 sec segments with no overlap.

I think setting the max iter higher would be ideal. maybe at least 200 but 500 seems good? will need to see how this performs, as i am not particularly familiar with the mne ica algorithem vs the ones eeglab uses. Go with 500 for now?

Why are you excluding the first two components before copying back? Sorry, I might have missed the explanation. 

For rejecting ica components, we will not use the ecg method any time soon (but maybe in the future?). The EOG method should be able to take any channels, even if they are not eog channels per se. What happens if you just identify the two most frontal channels and pass those as EOG for now? Ultimately, we will need a better method for ica identification. I will look into this further. 

Lastly, yes, you definitely want to add a 1 hz highpass filter to the copied data before you segment it. Very sorry for leaving that out of the feature description. I have updated the feature description above to add it back in.

One other comment: the main reason we segment the data before ica is to find segments that are bad and to remove those. I did not see somewhere in your code where you are currently doing that? Can you please loop in @Jonhas and @SDOsmany to ask about automated rejection methods? 

Thank you!!

**Comment by yanbin-niu** [comment]
@georgebuzzell 

1. About "I think setting the max iter higher would be ideal. maybe at least 200 but 500 seems good? will need to see how this performs, as i am not particularly familiar with the mne ica algorithem vs the ones eeglab uses. Go with 500 for now?"

It mentions in https://mne.tools/stable/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html#using-an-eog-channel-to-select-ica-components

> MNE-Python implements three different ICA algorithms: fastica (the default), picard, and infomax. FastICA and Infomax are both in fairly widespread use; Picard is a newer (2017) algorithm that is expected to converge faster than FastICA and Infomax, and is more robust than other algorithms in cases where the sources are not completely independent, which typically happens with real EEG/MEG data.

So, I just used picard as recommended. (not sure which one is better. and I remember in EEGlab tutorial, infomax performs good )

2. "Why are you excluding the first two components before copying back? Sorry, I might have missed the explanation."
I did this randomly, coz I did not find something about automatically identify artifactual independent components (ICs). (Will update the script based on your comments.)

3. "One other comment: the main reason we segment the data before ica is to find segments that are bad and to remove those. I did not see somewhere in your code where you are currently doing that?"

I did this in 

```
# detect epochs - that are excessively “noisy” for any channel
reject_criteria = dict(eeg=150e-6)       # 150 µV
flat_criteria = dict(eeg=1e-6)           # 1 µV

# arbitrary 1-second epochs & remove "noisy" data
epochs_prep = mne.Epochs(raw_filtered_1,
                    events=new_events,
                    tmin=0,
                    tmax=1,
                    baseline=None,
                    reject=reject_criteria,
                    flat=flat_criteria,
                    preload=True)

```

See https://mne.tools/stable/generated/mne.Epochs.html?highlight=mne%20epochs#mne.Epochs
we can do removing while doing segmentation. Of course, we also can do segmentation first and drop bads:

```
epochs_prep = mne.Epochs(raw_filtered_1,
                    events=new_events,
                    tmin=0,
                    tmax=1,
                    baseline=None,
                    preload=True)

# detect epochs -that are excessively “noisy” for any channel
reject_criteria = dict(eeg=150e-6)       # 150 µV
flat_criteria = dict(eeg=1e-6)           # 1 µV

epochs_prep.drop_bad(reject=reject_criteria, flat=flat_criteria) 
```

**Comment by georgebuzzell** [comment]
@yanbin-niu 

This all sounds great. I am familiar with infomax and fastica from eeglab, but had not heard of picard. Sounds good to me to go with picard and 500/1000 iter for now. We can more rigorously investigate later. Thank you for taking the initiative to look into this; you are now teaching me about EEG processing! :)

I feel silly for missing the now obvious section of code for rejecting segments based on artifacts. Thank you for clarifying! Your rejection code looks great. However, one important change is to use rejection of 1000 uv here. This is because we only want to reject excessively noisy data before ica. Later, at the end of the processing stream, we will use a rejection cutoff of 150 like you originally did, to catch any residual artifacts missed by ica. Does that make sense? Happy to clarify this if not, as it might be confusing.

@yanbin-niu Just want to say again that you continue to impress me; thank you so much for all of your contributions and it is awesome to see how quickly you are picking things up (and now teaching me!).

**Comment by yanbin-niu** [comment]
@georgebuzzell Thanks for the nice words! Honestly, I have no idea about all sorts of algorithms. To me, they are merely different combinations of characters.....

The rejection cutoff of 1000 uv makes sense! Sorry for missing this one early on.

So, based on your comments, the tentative script for ica feature seems:

```
import pathlib
import matplotlib
import mne
import mne_bids
matplotlib.use('Qt5Agg')
mne.set_log_level('warning')

# Read BIDS data
bids_root = pathlib.Path('raw_data/eegmatchingpennies')
bids_path = mne_bids.BIDSPath(subject='05',
                              task='matchingpennies',
                              datatype='eeg',
                              root=bids_root)

raw = mne_bids.read_raw_bids(bids_path)
raw.set_montage('standard_1020')

# prepica
# High-pass with 1. Hz cut-off is recommended for ICA
raw_filtered_1 = raw.copy()
raw_filtered_1 = raw_filtered_1.load_data().filter(l_freq=1, h_freq=None)

# make 1s events
new_events = mne.make_fixed_length_events(raw_filtered_1, id=99999, duration=1.)

# detect epochs - that are excessively “noisy” for any channel
reject_criteria = dict(eeg=1000e-6)       # 1000 µV
flat_criteria = dict(eeg=1e-6)           # 1 µV

# arbitrary 1-second epochs & remove "noisy" data
epochs_prep = mne.Epochs(raw_filtered_1,
                    events=new_events,
                    tmin=0,
                    tmax=1,
                    baseline=None,
                    reject=reject_criteria,
                    flat=flat_criteria,
                    preload=True)

# ica
method = 'picard'
max_iter = 500
fit_params = dict(fastica_it=5)
ica = mne.preprocessing.ICA(n_components=None,
                            method=method,
                            max_iter=max_iter,
                            fit_params=fit_params)
ica.fit(epochs_prep)

ica.plot_components(inst=epochs_prep)
ica.plot_sources(epochs_prep)

# detect eog & exclude it
eog_indices, eog_scores = ica.find_bads_eog(epochs_prep, ch_name='FC1')
ica.exclude = eog_indices

# reapplying the matrix back
reconst_raw = raw.copy()
raw_cleaned = ica.apply(reconst_raw.load_data())
```

A quick question is, for this example data, ten electrodes are : FC5, FC1, C3, CP5, CP1, FC2, FC6, C4, CP2, CP6. So I used 'FC1' (also tried 'FC2'). Do you think it is ok?

Another strange thing is, the code

```
# detect eog & exclude it
eog_indices, eog_scores = ica.find_bads_eog(epochs_prep, ch_name='FC1')
ica.exclude = eog_indices
```

eog_indices is empty, which means we will NOT exclude any component. and when I checked the eog_scores, it seems the component 0 should be the EOG. Notice that the score may be not high enough (in the tutorial, it's approaching 1.0), so I guess maybe there is something to do with the eog_scores?

<img width="728" alt="image" src="https://user-images.githubusercontent.com/79607547/115586991-bd3a3200-a2ff-11eb-8142-610103b9246c.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/79607547/115587029-c9be8a80-a2ff-11eb-8bdb-daf328e54c11.png">
(Thanks god, this is the only type of figure I can plot with my computer now)

**Comment by georgebuzzell** [comment]
Looking great! 

Yes, FC1 and FC2 would be the ones to choose here. By the way, for a real data analysis, we would NEVER try to do ICA rejection of blinks with so few electrodes. Typically, you want something closer to 32 or so as a lower limit (but you might be able to do it with something like 20; just not 8!). However, to be clear, what you are doing is correct, as we are just trying to get the code working, and will switch to using the data that @DMRoberts is importing using feature-io.

I don't think anything is wrong with your code just becuase nothing is being removed. Instead, this just relates back to us using this low channel number data set. Sorry for the confusion! To fully test your code, we will want to use a dataset with more electrodes.

@DMRoberts do you think you have a file from import-io that @yanbin-niu and others could start using?

PS @yanbin-niu : "(Thanks god, this is the only type of figure I can plot with my computer now)" LOL! :) I do hope you are able to resolve this!!

Thanks again!

**Comment by yanbin-niu** [comment]
@georgebuzzell Some updates based on the testing the script with our BIDS data:

1. Graph before vs after implementing 1hz high-pass filter:
![image](https://user-images.githubusercontent.com/79607547/116054795-a5233380-a6ae-11eb-9b0e-df9983db85d5.png)
![image](https://user-images.githubusercontent.com/79607547/116054826-ad7b6e80-a6ae-11eb-8a7e-f2bc3d6f0ac8.png)

It seems the data is still very "noisy". I double checked with the code from feature-filter and I got the same result. So, I assume this is because we have many "large" amplitude signals and we did not set low-pass filter for this step;

2. while running previous code for "arbitrary 1-second epochs & remove "noisy" data", there will be no data left if we set the 1000uv.... If I loosed the criterion to 3000 uv, 70% data will be left. This kind of gets in line with my first point. I think this may because we do not have bad-channel feature. And epoch works like: any one channel exceeds the rejection threshold, the respective epoch will be dropped. Of course, it also would because our data is just too "noisy". We may want some low-pass filter?

3. After setting a low-pass filter (50hz), using rejection cutoff of 1000 uv, running ICA. (I tried low-pass filter since the ICA can not converge with 200 iter). The result log and graph of components are:

> <ICA | epochs decomposition, fit (picard): 89178 samples, 128 components, channels used: "eeg">

![image](https://user-images.githubusercontent.com/79607547/116057530-78245000-a6b1-11eb-8831-3ba25d025937.png)

graph of sources:
![image](https://user-images.githubusercontent.com/79607547/116057748-b28ded00-a6b1-11eb-9a28-c443402dc90a.png)

4. while removing artifacts, I selected E126 and component 40 and 0 have been identified as EOG artifacts.
![image](https://user-images.githubusercontent.com/79607547/116060595-95a6e900-a6b4-11eb-823b-1105e64afed1.png)

component 40:
![image](https://user-images.githubusercontent.com/79607547/116064766-e8829f80-a6b8-11eb-8fd9-2124c3ebd9e2.png)

But, actually this can vary a lot based on the different electrode I selected. Along with the risk being mentioned in the tutorial, 

> If you don’t have an EOG channel, find_bads_eog has a ch_name parameter that you can use as a proxy for EOG. You can use a single channel, or create a bipolar reference from frontal EEG sensors and use that as virtual EOG channel. This carries a risk however: you must hope that the frontal EEG channels only reflect EOG and not brain dynamics in the prefrontal cortex (or you must not care about those prefrontal signals).

How do you think @georgebuzzell ?

**Comment by georgebuzzell** [comment]
@yanbin-niu this is SUCH GREAT WORK! Responses below:

"while running previous code for "arbitrary 1-second epochs & remove "noisy" data", there will be no data left if we set the 1000uv.... If I loosed the criterion to 3000 uv, 70% data will be left. This kind of gets in line with my first point. I think this may because we do not have bad-channel feature. And epoch works like: any one channel exceeds the rejection threshold, the respective epoch will be dropped. Of course, it also would because our data is just too "noisy". We may want some low-pass filter?"

"After setting a low-pass filter (50hz), using rejection cutoff of 1000 uv, running ICA. (I tried low-pass filter since the ICA can not converge with 200 iter)."

-Great insights here. Yes, you are correct as to why data is being rejected. Two slight changes to your approach: You want to run the HIGH PASS filter, as opposed to the low pass filter. The high pass filter will remove all the large, slow drifts. Let's leave off the low pass for now. So, please try with the high pass (.3 hz) and then reset the rejection to 1000 uv and see how that does?

For the question about EOG rejection, yes, good points. We actually want to provide a vector of ocular electrodes. Can you please plot the channel locations with their names so that we can identify the proper eog channels to use here? Here are the ones we want to use:

![image](https://user-images.githubusercontent.com/71228105/116229810-ed7d3880-a724-11eb-913f-8137b90cf51e.png)

**Comment by yanbin-niu** [comment]
@georgebuzzell 

I tried high pass .3 and 1000 uv. Also no data left. I think it makes sense, since previously we have 1hz high pass. Setting to .3 kind of means we have more signals?

I plotted the locations of sensors, 
![image](https://user-images.githubusercontent.com/79607547/116287243-c4ab8080-a7c2-11eb-91b2-b76d42ece8a3.png)

One thing you may want to know, `ica.find_bads_eog` only receives a channel name for `ch_name` parameter. 
https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.find_bads_eog
<img width="829" alt="image" src="https://user-images.githubusercontent.com/79607547/116287763-5b783d00-a7c3-11eb-8945-2041b13c5145.png">

However, MNE has `set_bipolar_reference` (https://mne.tools/stable/generated/mne.set_bipolar_reference.html?highlight=bipolar%20reference#mne.set_bipolar_reference):

> Re-reference selected channels using a bipolar referencing scheme.
> 
> A bipolar reference takes the difference between two channels (the anode minus the cathode) and adds it as a new virtual channel. The original channels will be dropped. 

It can receive a list of channel names for both anode and cathode.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/79607547/116288122-c32e8800-a7c3-11eb-8372-31a3e68ebf76.png">

If this seems work. Let me know, which channels we wanna use as anode and cathode respectively. I will try and see.

**Comment by yanbin-niu** [comment]
@georgebuzzell I just realize `set_bipolar_reference` might not work as well, since it will remove the original channels. :(

**Comment by georgebuzzell** [comment]
@yanbin-niu thank you for plotting this! 

The EOG channels we will want to use are: E127, E126, E25, E8

Correct, we DO NOT want to create a bipolar reference for the ocular. 

Sorry, good point, you should run it with 1 hz highpass and 1000 microvolts. Does that keep a majority of the data?

**Comment by yanbin-niu** [comment]
@georgebuzzell Sorry if I did not make the point clear. Early on I run with 1 hz highpass and 1000 microvolts and no data left.

`ica.find_bads_eog` only receives a channel name for `ch_name` parameter. So, we can not use 4 channels. I will do more research on this (but I doubt I will find something...).

**Comment by georgebuzzell** [comment]
@yanbin-niu Ah, OK, sorry, I misunderstood. Yes, that does seem to be an issue for there being no data left after the 1 hz highpass... 

I will need to look into this further as well. Both for the voltage rejection issue, and the eog channel issue.

**Comment by georgebuzzell** [comment]
@yanbin-niu I think it might be good to try this python ADJUST implementation for the identification of bad ics. This means we no longer have to identify a single ocular channel as well. https://github.com/mdelpozobanos/eegadjust

**Comment by yanbin-niu** [comment]
made initial PR https://github.com/NDCLab/baseEEG/pull/162.

Remaining issues:
1. montage information should be get from `user_params.json` or “eeg.json” sidecar file (is it possible? @DMRoberts );
2. let the user decide on the rejection criterion for bad epochs? @georgebuzzell  remember that with 1000uV, there will be no data left;
3. artifacts identification -- should not use current `find_bads_eog` which is just based on one channel -- @yanbin-niu try ADJUST (https://github.com/mdelpozobanos/eegadjust)

**Comment by F-said** [comment]
close with merge of #162
