### ISSUE TITLE
Fix IR3 Code

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#294]
**Describe the bug**
Test case fails as described below.

**Expected behavior**
Test case should run correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/26397102/131139671-161396f6-ccad-4dea-afa1-cdbc262e664b.png)

**Comment by F-said** [comment]
Consider what errors could occur while using the ica function:

- user tries to use silly data (ex: pd dataframe) w/filter *TypeError*
  - **hard stop** maybe? don't try to preprocess garbage data. Need feedback on this as well.

**Comment by SDOsmany** [comment]
> Consider what errors could occur while using the ica function:
> 
> * user tries to use silly data (ex: pd dataframe) w/filter _TypeError_
>   
>   * **hard stop** maybe? don't try to preprocess garbage data. Need feedback on this as well.

What would be a good reason to hard stop the preprocess of silly data?

Instead of a hard stop maybe is better to just notify that the data is silly.
