### ISSUE TITLE
Building the latest Docker image fails due to matplotlib version specified

### ISSUE THREAD

**Issue by DMRoberts** [NDCLab/baseEEG#31]
Building the latest docker image, with:

`docker build -t base_eeg .`

Fails with the following error:

```
#10 22.79 ERROR: Could not find a version that satisfies the requirement matplotlib-base==3.3.4 (from -r requirements.txt (line 51)) (from versions: none)
#10 23.04 ERROR: No matching distribution found for matplotlib-base==3.3.4 (from -r requirements.txt (line 51))
```

It seems that the requirements file specifies matplotlib 3.3.4, but the latest version available may only be 3.4.1?: [https://pypi.org/project/matplotlib](https://pypi.org/project/matplotlib)

**Comment by DMRoberts** [comment]
I must have been confused earlier, since 3.4.1 (the newest version) is > 3.3.4 (the version specified). I think the issue may be that we only need to specify matplotlib in the requirements.txt and not both matplotlib-base. Pip does seem to install matplotlib v 3.3.4 .

**Comment by yanbin-niu** [comment]
@DMRoberts My bad. I should have had it fully tested. I will do a pull request later.

**Comment by georgebuzzell** [comment]
@DMRoberts we were also having issues with the docker build for pyqt. You and I both experienced that issue. However, did you resolve that issue as well? 

@yanbin-niu

**Comment by yanbin-niu** [comment]
@georgebuzzell Yes. I am working on building the image. My internet for downloading is really slow (might have something to do with being outside of the US ), so will take longer time to do the test.

**Comment by georgebuzzell** [comment]
@yanbin-niu THANK YOU! :)

Btw, @yanbin-niu I also should have caught this when I reviewed your pull request, so my bad too!! Sorry for not catching this. We are all learning here... :)

**Comment by yanbin-niu** [comment]
@georgebuzzell Totally my fault. I really should have had this fully tested. Now, I am stuck in downloading mayavi and doing more test (it takes me forever...). For now, can we roll back to the old requirement.txt (after @DMRoberts included the mneBIDS and pybv ) and I just added a matplotlib? -- so people will not be hold off and can move forward. I have this requirements.txt tested and it looks good. I made a new pull request. If @georgebuzzell you agree, please review the pull request. (Sorry again for this big bug...).

**Comment by georgebuzzell** [comment]
Thanks again, @DMRoberts and @yanbin-niu!

I made sure to fully test the docker build/run this time before merging. :)
