### ISSUE TITLE
Potentially modularize preprocess.py

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#312]
**Background**
Decide b/w condensing or keeping the preprocess.py file 

**Defined as Done**
Decision is made

**Comment by F-said** [comment]
@stevenwtolbert @DMRoberts 

For this codebase, would it be better to further separate out preprocess.py into separate modules or keep current implementation? Separating may help with merging w/o conflicts.

**Comment by DMRoberts** [comment]
I think preprocess.py could be broken up into submodules if there is a logical grouping, I just wouldn't suggest putting each function into its own submodule / file since that is unusual for Python.

**Comment by georgebuzzell** [comment]
i agree with both of you here, @DMRoberts and @F-said . I agree we want to break up preprocess.py a bit, but only into logical submodules, and not every function in its own submodule.

so, we could put all the bad channel detection functions in one submodule, all the ica-related steps together in one submodule, for example. 

can someone perhaps propose a list of the submodules we would move to? @F-said @yanbin-niu ?

**Comment by F-said** [comment]
Here's how I propose to split up the preprocess module without relegating each function to its own file @DMRoberts @georgebuzzell : 

## preprocess.py 

reref_raw(raw, ref_channels=None)

segment_data(raw, tmin, tmax, baseline, picks, reject_tmin, reject_tmax, decim, verbose, preload)

filter_data(raw, l_freq=0.3, h_freq=40)

final_reject_epoch(epochs)

identify_badchans_raw(raw)

interpolate_data(epochs, mode, method, reset_bads)

## ICA.py

ica_raw(raw, montage)

hurst(data)

## visualize.py

plot_sensor_locations(epochs, user_params)

plot_orig_and_interp(orig_raw, interp_raw)

Any other function that gets helper functions in the future will additionally become its own module.

**Comment by F-said** [comment]
In retrospect, it seems like preprocess.py is actually perfectly fine for merging in changes over multiple functions. (merge conflict resolution was a tiny resolve). Maybe unnecessary issue.

**Comment by F-said** [comment]
close for now
