### ISSUE TITLE
Metadata file seems to be missing example participant

### ISSUE THREAD

**Issue by DMRoberts** [NDCLab/baseEEG#32]
The metadata file - "HBN_R1_1_Pheno.csv", with age and gender (coded as 0 or 1, gender mapping is currently unclear) in the following folder seems to be missing data for the example participant (NDARAB793GL3)

 https://drive.google.com/drive/u/0/folders/1e0BrDX6GMlDhR2OiL_m-ogWMEiHKD6JE

**Comment by georgebuzzell** [comment]
@DMRoberts thank you for pointing this out. I will take a look!

**Comment by georgebuzzell** [comment]
@DMRoberts what happens when the code you pushed runs, given that it looks in the metadata file for the participant's metadata? Does it simply skip writing particular fields of the metadata file?

**Comment by DMRoberts** [comment]
It's not currently writing the age or gender of the participant for anyone (regardless of whether they are in the metadata file or not), I just waited on implementing that until this issue was resolved.

**Comment by georgebuzzell** [comment]
@DMRoberts I uploaded a second pheno file, which contains the pheno data for this participant. Please see here: https://drive.google.com/file/d/1xdw4WkX2cjX7cKDNQemTb5TqtsLMYZrQ/view?usp=sharing

Basically, CMI releases these data in batches, and somehow, I pulled example files for us to work with from one batch, but uploaded the pheno file from another batch; my apologies!
