### ISSUE TITLE
The issue related to removing the reference channel prior to ICA

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#321]
The current ICA receives a parameter for the reference channel. In the copied data, the reference channel is removed, but not for the raw data. -- should be fixed, so that the reference channel should not be removed in both the copied data and the raw data.

**Comment by yanbin-niu** [comment]
@DMRoberts do you mean we should receive a parameter that indicating the dimension for PCA or we should rely on PCA to do the automatic dimension reduction?

I did some tests on this early on. If I remember it correctly -- for example, we have 64 channels, including Cz as the reference channel. Even if I do not remove the Cz in the copied data, the PCA step will still go down to 63. But not sure whether the PCA step will do the same thing for the average reference channel.

**Comment by DMRoberts** [comment]
Sorry @yanbin-niu I missed this comment earlier, I think we should be okay to rely on the MNE PCA / ICA procedure to determine the rank. It should work for the average reference case in the same way as your example with Cz as an included reference.

**Comment by yanbin-niu** [comment]
@DMRoberts thanks for the comment. That sounds good!

**Comment by F-said** [comment]
closing on merge #324
