### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#341]
**Describe the bug**
When running the pipeline in the current conda environment, the following error occurs
```
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found.`
```

**Expected behavior**
Container should be stable and not fail.

**Comment by georgebuzzell** [comment]
@F-said is this new behavior? Or a new test? If new behavior, do we have an idea what changes drove the error?

**Comment by F-said** [comment]
@georgebuzzell New behavior. A bug like this happened before and was resolved by updating a package in the `environment.yml` file

**Comment by F-said** [comment]
Probably local. Run on

- dockerfile
- singularity
