### ISSUE TITLE
Agenda 2021-10-08

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#346]
**Updates**

- #341 is specific to @F-said, autoreject works in containers
- #290 complete. Saved ~3TB @DMRoberts 
- #342 additions
  - #344 
  - #340 (removed ambiguities) 
  - Converted ndarrays in ICA to lists to avoid json error message
  - Converted int64 to str in ICA to avoid json error message
  - #336 
  - Updated hpc scripts to reflect new structure
  - Changed Final Reject output dictionary to match other features output dict
  - #345 

**Blocks/Challenges**

- Final_reject always skips subject with message `Data must be preloaded`. Implemented a quick-fix in #342 by loading data again, even though it is loaded in `ica_raw` and `filter_data`.
![image](https://user-images.githubusercontent.com/26397102/136566248-fd766000-7a5c-47c2-890f-f6b5c32f8086.png)

**Next Actions**

- #328 
- #287 
- [Rescheduling code review](https://www.when2meet.com/?13199811-VerXP)
- #349
- recheck #348
- recheck #347

Interesting competition: https://www.eegmanypipelines.org/

**Comment by georgebuzzell** [comment]
Discuss roadmap: https://docs.google.com/document/d/1Ug6i-mz5eaBYZxBwjBLDdqcVsu-yE3xqTivFpw8Bcg4/edit?usp=sharing
-especially need to discuss governance structure

-updates on pre-release
-updates on white paper (and timeline)

**Comment by F-said** [comment]
## Issues
* potentially run automatic pytest on docker on changes to `main` and `dev`
  * via github actions
  * via jenkins 
* reinit conda env on local @F-said 
  * troubleshooting 
* Propose rough draft on governance
