### ISSUE TITLE
Volume vs bind mount for docker

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#36]
From @DMRoberts: The script also took much longer to complete in the Docker container, about 28-29 minutes, vs. about 2 minutes to complete when running natively. I think some of this might be able to be alleviated by putting the data in a Volume:

https://stackoverflow.com/questions/55951014/docker-in-macos-is-very-slow
https://docs.docker.com/storage/volumes/

_Originally posted by @DMRoberts in https://github.com/NDCLab/baseEEG/issues/16#issuecomment-817462221_

**Comment by georgebuzzell** [comment]
Origionally posted by @DMRoberts in other issue: @georgebuzzell I ran the Docker container with the command in the readme:

docker run --rm -it -v $(PWD):/projects -w /projects dockerImage:Version bash

The Docker docs say -v means Bind mount a volume

The terminology is a bit confusing, because -v is described as 'bind mount a volume', but in other places, it seems that bind mounts are described in contrast to volumes, e.g.:

Here: https://docs.docker.com/storage/volumes/ :

Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. While bind mounts are dependent on the directory structure and OS of the host machine, volumes are completely managed by Docker. Volumes have several advantages over bind mounts:

Or Here: https://docs.docker.com/storage/ :

Volumes are stored in a part of the host filesystem which is managed by Docker (/var/lib/docker/volumes/ on Linux). Non-Docker processes should not modify this part of the filesystem. Volumes are the best way to persist data in Docker.

Bind mounts may be stored anywhere on the host system. They may even be important system files or directories. Non-Docker processes on the Docker host or a Docker container can modify them at any time.

I think what we're currently doing is a bind-mount, which links the host file system to the file system inside the container. This allows someone to edit / save the code in their native environment and run it inside the container, but it also makes loading and saving the data very slow.

**Comment by georgebuzzell** [comment]
Cross-posting from here: https://github.com/NDCLab/baseEEG/issues/16#issuecomment-818232841


@DMRoberts this is really helpful. It sounds like this is essentially what I brought up at our last meeting on 4/9? Or perhaps I am misunderstanding here?

I see your point that the terminology gets quite confusing here! Whatever we want to call it (and I think we want to call it "volumes") we want to use docker in such a way that our code running inside docker references directories inside docker, which are not dependent on the local machine's path structure. I think what we need to confirm, is exactly what code will allow for that, as there seems to be some confusion as to whether the way we are currently running the docker image does this or not. @Jonhas any thoughts here?

I will look closer at the documentation you sent, @DMRoberts. Very helpful. Thanks!!

**Comment by Jonhas** [comment]
@georgebuzzell @DMRoberts I completely agree how confusing the terminology can be. We definitely should refer to it as volumes moving forward. Considering how --mount and -v are used interchangeably, I realized how confusing the documentation can be when I ran 
`docker volume ls ` 
and nothing shows up haha. Volumes are preferred for it removes dependencies on one's own host system, allows for easy distribution, and improves performance. The following link https://phoenixnap.com/kb/docker-volumes and the documentation Dan provided can help solve this issue.

**Comment by georgebuzzell** [comment]
Thank you @Jonhas and @DMRoberts 

OK, so I am still confused here. we have been using the following when laucnhing our docker container:

-v $(PWD):/projects

Based on the documentation, it is clear that "-v" can be used EITHER to specify a bind mount or a volume mount. It seems like @DMRoberts is saying that use of "-v" above creates a bind mount. It seems like @Jonhas is saying this creates a volume mount.

From reading the doc here: https://docs.docker.com/storage/bind-mounts/
![image](https://user-images.githubusercontent.com/71228105/114865355-1fef7300-9dc0-11eb-9e00-2ab255ab48e5.png)

and here: https://docs.docker.com/storage/volumes/
![image](https://user-images.githubusercontent.com/71228105/114865390-2d0c6200-9dc0-11eb-8f20-ef099cf305d3.png)

It seems to me that "-v $(PWD):/projects" is in fact creating a bind mount. No? @Jonhas @DMRoberts 

Relatedly, it might be preferred for us to just switch away from "-v" altogether and use a more verbose "--mount" command to avoid confusion?

**Comment by yanbin-niu** [comment]
@georgebuzzell I believe the “myvol2” in the second picture is the name for the volume created by "docker volume create myvol2". For the volume mounts, we do not give a path, since docker will put it in a fixed place in the host (/var/lib/docker/volumes). but for bind mounts, we have to specify a path, and `docker run` will copy everything in that folder into the container. So, I think one thing we need paying attention to is, if we switch to volume mounts, we have to copy our code and data into myvol2 first.
