### ISSUE TITLE
read bids-eeg doc

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#4]
https://www.nature.com/articles/s41597-019-0104-8

**Comment by Jonhas** [comment]
Really interesting paper, goes in depth on explaining the new data structure, BIDS for EEG data, and the project organization for some product that may be using it.

**Comment by georgebuzzell** [comment]
Glad you took a look! Yeah, it is very nicely detailed.

**Comment by DavyNeat** [comment]
Finished Reading.

**Comment by georgebuzzell** [comment]
@SDOsmany @Pranjali051 @yanbin-niu Please comment if/when you read this. I think I will close the issue once all read it. thanks!

**Comment by SDOsmany** [comment]
I already finished reading it aswell

**Comment by Pranjali051** [comment]
I finished reading it last week.

**Comment by yanbin-niu** [comment]
I finished reading it as well!
