### ISSUE TITLE
JSON cannot parse tuples

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#401]
**Describe the bug**
JSON cannot parse tuples, problem if we need tuples for data

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26397102/142513569-86eef632-fc05-4833-9944-a902334a62e0.png)

**Comment by DMRoberts** [comment]
@F-said Do you have the code or configuration that generated the error?

**Comment by F-said** [comment]
@DMRoberts It looks like MNE does some type-checking [here](https://github.com/mne-tools/mne-python/blob/bf5bd43973e30fe80d93436a7f5cae9e9eeb766f/mne/baseline.py#L127). We may need to handle this by going from list to tuple inside of `segment_data`

![image](https://user-images.githubusercontent.com/26397102/142770367-0269f304-5270-40dd-8320-3d61a4979379.png)

**Comment by F-said** [comment]
Marking resolved for now #410
