### ISSUE TITLE
figure out jupyter-github integration

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#5]
All can work and research this at the same time. please comment on this issue with what you find. test out new github actions, plugins, etc as needed. if you need upgraded permissions, just let me know!

**Comment by georgebuzzell** [comment]
Check out:
nbviewer
ReviewNB

Is anyone interested in taking a look and trying to implement? @Jonhas @SDOsmany @DavyNeat

**Comment by Jonhas** [comment]
I believe trying to implement ReviewNB, it requires for the owner of the repo to do it. When trying to install it via the GitHub marketplace, it would not allow me to install it to the baseEEG repo.

**Comment by georgebuzzell** [comment]
@Jonhas I will go ahead and make you, and the others, owners of the repo!

**Comment by georgebuzzell** [comment]
@Jonhas @DavyNeat @SDOsmany @CamachoBry @stevenwtolbert @Pranjali051 You have all been invited to the base-eeg-team. Once you accept that invite, you should have full admin access to this repo, as I gave full admin access to that team. 

@Jonhas once you join the team, can you please let me know if it allows you to install ReviewNB?

**Comment by Jonhas** [comment]
![Capture](https://user-images.githubusercontent.com/45021859/110860442-62cea000-8282-11eb-8a37-76a0a9b12101.PNG)

**Comment by georgebuzzell** [comment]
@Jonhas and @SDOsmany Thank you for trying! I will go ahead and try installing as the owner as the organization and then update you all.

**Comment by georgebuzzell** [comment]
Separate note: did you all have a chance to look into nbviewer at all as well?

**Comment by georgebuzzell** [comment]
i think i installed it for the org, but not clear. @Jonhas and @SDOsmany can you please take a look?

**Comment by Jonhas** [comment]
Within the repository settings on settings>integration, it says that it was able to install ReviewNB successfully. So I guess it worked out! Thank you for the help. I did take a look at NBviewer as well. However, it seems to be simply a sharing platform of notebooks rather than a fully GitHub integrated collaborative platform. NBviewer allows others to share jupyter notebooks as a static html file or through a Binder application
