### ISSUE TITLE
determine whether base linux image is needed in docker

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#58]

**Comment by stevenwtolbert** [comment]
Ok, so good thing we looked into this. It appears that docker uses the host OS kernel, which of course will vary across all distributions of the image no matter how you've set up your docker environment. This process is shown in the diagram below. 

![image](https://user-images.githubusercontent.com/40587948/116186785-28f21580-a6d9-11eb-9431-a5bb6a9fc0b2.png)

This allows for multiple docker images to be run with minimal overhead at the cost of possible compatibility issues in the future. 

The only way to get around using the host OS kernel is to run a full VM. Virtual machines are able to make system calls through three processes detailed in Modern Operating Systems by Andrew Tanenbaum: 

> There are 3 common strategies to handle this:
> 1. Hypervisor traps system calls from guest: The hypervisor checks whether the privileged instruction(effectively system call) came from the guest OS itself, or from a user-space program within the guest OS. If it's the former case, then the hypervisor will actually forward the call to the hardware, although through the virtualization instructions. If it's the latter, the hypervisor will redirect the call to the guest OS, and then proceed.
> 
> 2. Binary translation: Here the hypervisor checks the code from the guest OS in what are called as "basic blocks", scanning for privileged instructions. Wherever it finds them, it replaces them with calls to it's own procedures to system calls. It then proceeds to cache these blocks & eventually builds a whole set of such blocks.
> 
> 3. Paravirtualization: Here the guest OS itself is modified so that instead of making calls to the hardware, it has APIs to invoke the hypervisor to get its hardware I/O done.

**Comment by georgebuzzell** [comment]
@stevenwtolbert thank you for looking into this!

Unfortunately, VMs might be too heavy.

Is this saying that even if you set up docker to load a complete linux image, the docker will still use the host kernal if running on linux? And what about if running on windows/mac?

Would there still be benefits to loading the entire linux base image if the host kernal is being used?

@DMRoberts @Jonhas

**Comment by georgebuzzell** [comment]
OK, I read up on this more, I get it now.

It seems like most of the issues in computational reproducibility come from: dependency differences and library differences. We are able to control for this by loading the linux base image (userland but not the kernal) and specific dependencies. I think this is good enough, at least for now.

One thing I am unclear on, is whether system calls are also controlled for in a docker container? I am not clear on this. This is another possible source of differences across OSs, so it would be good to know at least.

https://www.frontiersin.org/articles/10.3389/fninf.2015.00012/full#note11

https://itnext.io/breaking-down-containers-part-0-system-architecture-37afe0e51770

@DMRoberts @Jonhas ?

**Comment by DMRoberts** [comment]
@georgebuzzell I believe one other detail is that since (Linux) Docker containers run on the Linux kernel, running containers on Mac (via Docker Desktop) actually starts a Linux virtual machine for the containers to run inside. I believe something similar happens with Docker Desktop for Windows, though using the Windows Subsystem for Linux. This is what contributes to the performance difference when running linux containers with a Linux Host OS vs. a Mac or Windows Host OS, because there is an extra layer of abstraction (the virtual machine running the linux kernel) is the latter two cases. I think there are also Windows Docker containers, running Windows applications on a Windows Host OS but those are less common.

I think the question then becomes whether the version of the host / vm Linux kernel influences reproducibility, and if so how can that be remedied.

**Comment by georgebuzzell** [comment]
@DMRoberts yes, exactly! I was discussing this with @stevenwtolbert yesterday. Basically, this is the deal: 

The docker container, like a basic conda environment improves reproducibility by fixing the dependencies loaded.

However, loading a base linux image in docker, although it will still use the host kernel, has the added benefit (in terms of reproducibility) over conda in terms of also loading all of userland. 

The catch, is that docker still relies on the kernel for system calls, which are a known source of variability in cog neuro (but less so than dependencies and userland). Thus, simply using docker will not ensure perfect reproducibility, though it is a big improvement.

The only way to ensure full reproducibility is through VMs, but that will compromise performance too much and would be inefficient for development, hence they are not viable.

Taking all into consideration, the plan moving forward is to stick with docker as we have been (and singularity for the server). Please keep in mind that most actual computing will take place on the linux hpc, which is also the direction that many labs are going. Thus, the performance of containers should not be an issue. Moreover, as long as we are explicit about using a linux machine when sharing our code, there is a low likelihood of variability at the system call level, given that most linux distros have a  very similar kernel and most variability exists at the level of userland (which will be fixed in our container).

@Jonhas @SDOsmany @yanbin-niu @DavyNeat
