### ISSUE TITLE
Agenda 4/30

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#76]
- [mne update 0.23.0](https://mne.tools/stable/whats_new.html#version-0-23-0)
    - For anyone that updated, do any methods behave differently?
    
- Project file structure of baseEEG 
    - Should it follow the [mne example](https://github.com/NDCLab/mne-study-template)
    
- Global annotations and log files
    - Write to path? Write to object? Are global variables OK in this context?

**Comment by georgebuzzell** [comment]
Additional items

Standards and CI

Annotations outside range

Docker and reproducibility
