### ISSUE TITLE
Fix/update branch structure for folder

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#8]
Should follow this convention:

main
->dev
-->dev-feature-[featureName]
--->dev-feature-[featureName]-[yourName]

Reminders:

1. only push directly (without code review) to dev-feature-[featureName]=[yourName]
2. Must initiate pull request (and assign at least one person) for any higher-level branch
3. Mandatory code review by one person for all pull requests

**Comment by georgebuzzell** [comment]
@Jonhas When updating the branch structure for your code, please also put it in a Jupyter file if you don't mind. I think that is what we decided on, right? I am very flexible on what format the code is in for development though, this is just my recollection...

**Comment by Jonhas** [comment]
Yes this is correct.  I also just fixed the branch structure. I have included a jupyter file in dev-feature-io-Jonhas within my most recent commit. Just to clarify, this notebook should exist within dev-feature-io or in dev?  Thank you for the help.
