### ISSUE TITLE
manual identification of bad channels 

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#86]
meeting to manually identify bad chans
🕵️📈

**Comment by F-said** [comment]
repinging @georgebuzzell for meeting to manually ident bad-chans. Should this be held off for "project backlog" for now?

**Comment by georgebuzzell** [comment]
Thank you, @F-said !! 

Actually, I do want to prioritize this. @yanbin-niu is going to continue working on FASTER and this will be helpful for her. Let's schedule a time for this at the meeting today.
