### ISSUE TITLE
Update readme with pipeline plan

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#87]
Branch off of Dev and modify the readme file to describe the agreed plan for pipeline organization
-For details, see here: https://github.com/NDCLab/baseEEG/issues/77

Create a pull request, link to this issues, and assign all as reviewers

Anticipate some discussion and edits during the pr, until all agree.

Done = pr closed.

For details, see here: https://github.com/NDCLab/baseEEG/issues/77

**Comment by F-said** [comment]
further discussion on pipeline in #106
