### ISSUE TITLE
Create function to collate all dictionaries and write to disk

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#88]
The plan for the pipeline is to have a main script that reads in a user_params.json file and then calls a series of functions to complete the steps of the pipeline. The steps proceed procedurally, in order. Each step in the main script involves calling a function a function that modifies the eeg file and creates a new output dictionary for that specific step. Thus, running through the main script results in a series of dictionaries being created (one for each step). What is needed, is a function, which is called at the very end of the main script, that collates all of these dictionaries and writes to disk as one output_preproc.json file.

1. Branch off of Dev and create function for collating dictionaries and writing a single output_preproc.json file for the participant (one file per participant).
2. Test the code.
3. Submit PR (please link to this issue), including test code, and assign a reviewer.
4. Done = PR closed.
5.

**Comment by georgebuzzell** [comment]
@DMRoberts Based on the conversation on the recent PR here: https://github.com/NDCLab/baseEEG/pull/89 It sounds like we should have each function return a uniquely named dictionary, and then, this function would collate all of them. Does this all sound correct to you?

@yanbin-niu Thank you for bringing this to our attention!
@F-said comments welcome as well!

**Comment by Jonhas** [comment]
I took a crack at this. I saw that the PR failed the pylint check, but it is because of either trailing whitespace or not enough whitespace after a character. However, none of it affects the logic of the script. Regardless, please take a look at PR #101 whenever you guys get the chance @georgebuzzell @DMRoberts @yanbin-niu @F-said

**Comment by georgebuzzell** [comment]
Thank you, @jessb0t !! Seeing this comment now after just commenting on the PR. Yes, totally agree the whitespace error is not a big deal, but, we should fix that to be consistent, right Do you know why those are being added in?

**Comment by jessb0t** [comment]
Adding the other J for whom @georgebuzzell's comment above was intended. ;) @Jonhas

**Comment by georgebuzzell** [comment]
@Jonhas please see above :)
