### ISSUE TITLE
Running notebook in the container / anaconda mne Issue

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#9]
Do you guys ever encounter this problem?

If I open my laptop -> run docker -> localhost:8888/tree, everything seems good and notebook is working on the folder as it should.
<img width="821" alt="image" src="https://user-images.githubusercontent.com/79607547/112907098-da744a00-911f-11eb-8922-235120542043.png">

Then, I exit the container.

Then, if I run notebook with anaconda mne environment, it actually goes to localhost:8889/tree and notebook is working on my whole computer.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/79607547/112907317-39d25a00-9120-11eb-9d5f-f22bbc334524.png">

Then, I deactivate & exit anaconda mne and then rerun the docker -> localhost:8888/tree, it still has full access to my computer as if it is working on my host rather than the container. The problem will not stop until I restart my laptop.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/79607547/112915728-896d5180-9131-11eb-8138-f1e5986e4987.png">

I just cannot understand what is the problem and how we can avoid it (besides restarting the computer)

**Comment by yanbin-niu** [comment]
It seems the notebook will use the 8888port, which means the 8888 port in the host will be used by the container and host at the same time. That actually causes the problem. So, if we project 8888container port in a different host port, say, 5000, it works now. The steps are:
1. docker run --rm -it -v $(PWD):/projects -w /projects -p 5000:8888 mybaseeeg:v1 bash
2. jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
3. use the url provided and change the 8888 into 5000. Or, localhost:5000/tree.

Then this problem should be solved

**Comment by georgebuzzell** [comment]
@yanbin-niu Do you mind adding the solution you identified to the readme file and including in your next pull request?
