### ISSUE TITLE
Create write_eeg_data function to write eeg data after each processing step

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#95]
Steps for this issue (further details below):
1. Branch off of dev to create dev-write-eeg-data 
2. Create function and test in isolation
3. Test function being called from within an existing feature function (e.g "feature-filter")
3. Submit PR
4. Done (for now) = PR reviewed and closed

Currently, the main script of the pipeline passes "raw" to a function in each step of the pipeline, in which something is done to the eeg data, and then "raw" is returned to the main script so that it can be passed to the next step/function. This is all good. In addition to this, though, we also want each function (corresponding to a given step, i.e. filtering, bad Chans removal, etc) to also make a copy of raw (locally), rename this copy to be eeg_XXX (eeg_filter, eeg_badchans, etc) and writes this to disk within BIDS formatted "derivatives" folder.

The reason for saving the data after each step is to allow someone to load in data from a particular step, without having to re-run all the pipeline steps from the start.

When writing to disk, the eeg_xxx data should be written to a particular folder location. Within the bids dataset folder:

BID_dataset/

->sub-01/
->->ses-01/
->->->eeg/
sub-01_task-TASKNAME_eeg

->derivatives/
->->preprocessed/
->->->sub-01/
->->->->ses-01/
->->->->->eeg/
sub-01_task-TASKNAME_eeg_filter
sub-01_task-TASKNAME_eeg_badChans
sub-01_task-TASKNAME_eeg_ica
sub-01_task-TASKNAME_eeg_segment
sub-01_task-TASKNAME_eeg_finalrej
sub-01_task-TASKNAME_eeg_interp
sub-01_task-TASKNAME_eeg_reref

Thus, when eeg_write_data writes data to disk, the function will need to first check if the "derivatives->preprocessed->sub-XX folder already exist, and if not, create it.

**Comment by georgebuzzell** [comment]
@F-said @yanbin-niu @Jonhas @DMRoberts @stevenwtolbert @SDOsmany @DavyNeat Any of you interested in working on this?

**Comment by SDOsmany** [comment]
@georgebuzzell I will start working on it

**Comment by SDOsmany** [comment]
@georgebuzzell what is the :
`sub-01/
EEG/
sub-01_task-TASKNAME_eeg `

 is that a folder inside of the :
`sub-01/
sub-01_task-TASKNAME_eeg_filter
sub-01_task-TASKNAME_eeg_badChans
sub-01_task-TASKNAME_eeg_ica
sub-01_task-TASKNAME_eeg_segment
sub-01_task-TASKNAME_eeg_finalrej
sub-01_task-TASKNAME_eeg_interp
sub-01_task-TASKNAME_eeg_reref`

**Comment by SDOsmany** [comment]
@Jonhas Hey I need some advice for creating this function
Do you think this is a good approach or do you see any drawbacks like having access to bids_path or bids_root for the file name etc.

Also, I'm not sure how to get the name of the function to add to the eeg_{function name}
![Screenshot_12](https://user-images.githubusercontent.com/58539319/118070946-d53c2900-b374-11eb-83af-cfdfb95ff241.png)

**Comment by georgebuzzell** [comment]
@SDOsmany I have updated the folder structure in the original comment above. sorry for the confusion. I am basing this off what i beleive is our most recent bids folder we are all using. 

BID_dataset/

->sub-01/
->->ses-01/
->->->eeg/
sub-01_task-TASKNAME_eeg

->derivatives/
->->preprocessed/
->->->sub-01/
->->->->ses-01/
->->->->->eeg/
sub-01_task-TASKNAME_eeg_filter
sub-01_task-TASKNAME_eeg_badChans
sub-01_task-TASKNAME_eeg_ica
sub-01_task-TASKNAME_eeg_segment
sub-01_task-TASKNAME_eeg_finalrej
sub-01_task-TASKNAME_eeg_interp
sub-01_task-TASKNAME_eeg_reref

@DMRoberts didn't we say we were going to put the raw bids data into a raw folder? If so, we should update filter-io right?

**Comment by yanbin-niu** [comment]
@georgebuzzell do you think we really need this function? I think it might just be a part of feature-io, since feature-io has all the info about participants, sessions, runs etc. @DMRoberts can separate this part from his code for each step to call. 

![image](https://user-images.githubusercontent.com/79607547/118526699-18cad480-b773-11eb-8e9f-50b249d06519.jpeg)

**Comment by SDOsmany** [comment]
- This module will be called after each Function

**Comment by georgebuzzell** [comment]
@SDOsmany Unless decided otherwise at the meeting today, let's move forward with the folder structure described above here: https://github.com/NDCLab/baseEEG/issues/95#issuecomment-840463003

Also, regardless of whether we decide today that we will move forward with the looping main script or not, the revised plan is for this feature to be called from the main script, after each function/step. The reason to do this, either way, is that if we decide NOT to go with the looping approach for main today, then we still have plans to switch to that in the next release, so it will make the transition easier if this function is already being called after each function in the main script (i.e. will not require edits to each function/feature.

@F-said

**Comment by F-said** [comment]
resolved with pr #155. Closing
